# Generated by Django 3.2.8 on 2021-12-15 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poll.misc_functions
import poll.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('merkle_hash', models.CharField(blank=True, max_length=64)),
                ('self_hash', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
            ],
            options={
                'db_table': 'Block',
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Constituency',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('motto', models.TextField()),
                ('symbol', models.ImageField(upload_to=poll.misc_functions.party_symbol_name)),
            ],
            options={
                'db_table': 'Party',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_n', models.CharField(max_length=320)),
                ('public_key_e', models.IntegerField(default=0)),
                ('has_voted', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Voter',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=0)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
                ('block_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='poll.block')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('criminalRecords', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.party')),
            ],
            options={
                'db_table': 'Candidate',
            },
        ),
    ]
