# Generated by Django 3.2.8 on 2021-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='block_id',
            field=models.IntegerField(null=True),
        ),
    ]
